# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2884480d107ec6e1128683e8e472f24df3ddc5bad57c90b0fe35c97ebef6b34012e6e18e3d9f97d8d549c782a61c7dbc613455d47417cee797a4343b006ffe99

test:
  secret_key_base: b0a3b5a4ce4c69a9af1741bb21d70114b630e017e966456101bcc7bf1c5dad0c938a7f272b49d7242684300eb828245428fb69ddb80d521c94a9d26d177154b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
